### PR TITLE
Fix for PWM tone in transmission

### PR DESCRIPTION
**Pull request by s1lviu**
Based on this info: https://github.com/egzumer/uv-k5-firmware-custom/issues/405#issuecomment-2087617024 I've changed the value for the tone to not be audible during the transmission.

### CODE REVIEW

**Review by armel — COMMENTED** [review]
I'll try this on the feature_update branch. If it works, I'll add it to v2.8. Thanks.

**Comment by s1lviu** [comment]
Great, @armel,
Thanks!

**Comment by s1lviu** [comment]
Hey, @armel 
Did you manage to test?
Thanks!

**Comment by armel** [comment]
Hello @s1lviu, yes, the change will be added in version 2.8.

Armel F4HWN

**Comment by armel** [comment]
Commit is [here](https://github.com/egzumer/uv-k5-firmware-custom/commit/a0da2d86034d19e1b393db1094c317f13c574300) :)

**Comment by s1lviu** [comment]
Great, I saw the PR still open and just wanted to see if everything is okay.
73

**Comment by jdornelas83** [comment]
Muito obrigado pela sua dedicação e empenho por este firmware.

**Pull request merged**
